services:
  backend:
    # image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n12197718/whiteboard:latest
    build: .
    container_name: whiteboard
    ports:
      - "5000:5000"
    command: ["python", "entry.py"]
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      AWS_PROFILE: main
      AWS_DEFAULT_REGION: ap-southeast-2
    volumes:
      - /home/damon/.aws:/root/.aws 


 
